server:
  port: 8091
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://PRODUCT-MICROSERVICE
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1